version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
hooks:
  AfterInstall:
   - location: deploy/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: deploy/start_bot
     timeout: 300
     runas: root